# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  omniauth_provider_key: 4afa3cd137d87891bd6957acf61872f6f91483866d615219e83204b8e0408973
  omniauth_provider_secret: d6f5a78ffd61dce21d63f8ab162bb29e2c078c2b61bf734b8c539c6d7dcfad9a
  github_omniauth_provider_key: <%= ENV["GITHUB_OMNIAUTH_PROVIDER_KEY"] %>
  github_omniauth_provider_secret: <%= ENV["GITHUB_OMNIAUTH_PROVIDER_SECRET"] %>
  remotty_site: https://www.remotty.net
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: n2jk-academy3.dev
  secret_key_base: 3221e794f794a867454049afbb32d8446168b7b3e2348eda66ee3452148ec3ca75c2a1a5ee49419a49d0ecd553fb250531ea22c71456ac09870fafb68d4eb618

test:
  secret_key_base: 5f3a97639d92e1588223ca4f6fd8684eb2e2dd7eaae51f599f15b3fe3bb03505c80b07f5a21289769d4b5b5574294620a5a12f3f4e52385fc85f286497eca2a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %> 
  github_omniauth_provider_key: <%= ENV["GITHUB_OMNIAUTH_PROVIDER_KEY"] %>
  github_omniauth_provider_secret: <%= ENV["GITHUB_OMNIAUTH_PROVIDER_SECRET"] %>
  remotty_site: https://www.remotty.net
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
